image: Visual Studio 2019
build:
  parallel: true
platform: x64
configuration: Debug
environment:
  matrix:
    - PYTHON: 27
    - PYTHON: 35
    - PYTHON: 36
    - PYTHON: 37
    - PYTHON: 38
      RUN_PRAAT_TESTS: 1
    - PYTHON: 27
      platform: x86
    - PYTHON: 38
      platform: x86
    - PYTHON: 27
      configuration: Release
    - PYTHON: 38
      configuration: Release
    - WHEELS: 1
    - WHEELS: 1
      platform: x86

branches:
  except:
    - travis
    - docs

install:
  - ps: |
      if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" } else { $env:CMAKE_ARCH = "Win32" }
      if ($env:WHEELS) {
        $env:PYTHON = 37
        if ($env:PLATFORM -eq "x64") { $env:CIBW_BUILD = "*-win_amd64" } else { $env:CIBW_BUILD = "*-win32" }
        $env:CIBW_SKIP = "pp*-*"
      }
      if ($env:PYTHON) {
        if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
        $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      }
  - python -m pip install --upgrade pip wheel # Needs to be `python -m pip` because pip executable is (potentially) replaced
  - if defined WHEELS ( pip install cibuildwheel )
  - if not defined WHEELS ( pip install --upgrade -r tests/requirements.txt )
build_script:
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - if not defined WHEELS ( md build && cd build && cmake -G "Visual Studio 16 2019" -A "%CMAKE_ARCH%" -DCMAKE_SUPPRESS_REGENERATION=1 -DCMAKE_CXX_FLAGS="/MP" .. )
  - if not defined WHEELS ( cmake --build . --config "%CONFIGURATION%" --target all_build -- /v:m /logger:%MSBuildLogger% )
  - if defined WHEELS ( md praat_build && cd praat_build && cmake -G "Visual Studio 16 2019" -A "%CMAKE_ARCH%" -DCMAKE_SUPPRESS_REGENERATION=1 -DCMAKE_CXX_FLAGS="/MP" .. )
  - if defined WHEELS ( cmake --build . --config Release --target praat -- /v:m /logger:%MSBuildLogger% && cd .. )
  - if defined WHEELS ( set PARSELMOUTH_EXTRA_CMAKE_ARGS=-DPREBUILT_PRAAT_DIR="%cd%\praat_build\praat" -DCMAKE_CXX_FLAGS="/MP" && cibuildwheel )
test_script:
  - ps: if ($env:RUN_PRAAT_TESTS) { $env:PYTEST_ADDOPTS="--run-praat-tests" }
  - if not defined WHEELS ( cmake --build . --config "%CONFIGURATION%" --target tests )
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels

deploy:
  provider: GitHub
  auth_token:
    secure: k/rbI8NyOne2TXwt49at6R7MfhL1gsMU257T++hJgCj7RsO+q6xpQfWkSqAMFfa7
  description: ''
  artifact: Wheels
  on:
    appveyor_repo_tag: true
  draft: true
